# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\custom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(908, 691)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.generate = QtWidgets.QPushButton(Dialog)
        self.generate.setGeometry(QtCore.QRect(340, 510, 160, 28))
        self.generate.setObjectName("generate")
        self.date1 = QtWidgets.QCalendarWidget(Dialog)
        self.date1.setGeometry(QtCore.QRect(10, 120, 411, 261))
        self.date1.setObjectName("date1")
        self.date2 = QtWidgets.QCalendarWidget(Dialog)
        self.date2.setGeometry(QtCore.QRect(480, 120, 411, 261))
        self.date2.setObjectName("date2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(440, 260, 50, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.backButton = QtWidgets.QPushButton(Dialog)
        self.backButton.setGeometry(QtCore.QRect(520, 510, 150, 28))
        self.backButton.setObjectName("backButton")
        self.homeButton = QtWidgets.QPushButton(Dialog)
        self.homeButton.setGeometry(QtCore.QRect(160, 510, 150, 28))
        self.homeButton.setObjectName("homeButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Custom Revenue"))
        self.generate.setText(_translate("Dialog", "Generate"))
        self.label.setText(_translate("Dialog", "To"))
        self.backButton.setText(_translate("Dialog", "Back"))
        self.homeButton.setText(_translate("Dialog", "Home"))
