# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\invoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(821, 667)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.consulting = QtWidgets.QLineEdit(Dialog)
        self.consulting.setGeometry(QtCore.QRect(350, 160, 160, 22))
        self.consulting.setAutoFillBackground(False)
        self.consulting.setText("")
        self.consulting.setObjectName("consulting")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(189, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 300, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.paid = QtWidgets.QLineEdit(Dialog)
        self.paid.setGeometry(QtCore.QRect(350, 260, 160, 22))
        self.paid.setText("")
        self.paid.setObjectName("paid")
        self.pending = QtWidgets.QLineEdit(Dialog)
        self.pending.setGeometry(QtCore.QRect(350, 310, 160, 22))
        self.pending.setText("")
        self.pending.setObjectName("pending")
        self.finishButton = QtWidgets.QPushButton(Dialog)
        self.finishButton.setGeometry(QtCore.QRect(310, 430, 93, 28))
        self.finishButton.setObjectName("finishButton")
        self.pendingButton = QtWidgets.QPushButton(Dialog)
        self.pendingButton.setGeometry(QtCore.QRect(450, 430, 161, 28))
        self.pendingButton.setObjectName("pendingButton")
        self.autofillButton = QtWidgets.QRadioButton(Dialog)
        self.autofillButton.setGeometry(QtCore.QRect(530, 310, 95, 20))
        self.autofillButton.setObjectName("autofillButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(189, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.xray = QtWidgets.QLineEdit(Dialog)
        self.xray.setGeometry(QtCore.QRect(350, 210, 160, 22))
        self.xray.setAutoFillBackground(False)
        self.xray.setText("")
        self.xray.setObjectName("xray")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.consulting, self.xray)
        Dialog.setTabOrder(self.xray, self.paid)
        Dialog.setTabOrder(self.paid, self.pending)
        Dialog.setTabOrder(self.pending, self.pendingButton)
        Dialog.setTabOrder(self.pendingButton, self.autofillButton)
        Dialog.setTabOrder(self.autofillButton, self.finishButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Invoice"))
        self.label.setText(_translate("Dialog", "Consulting"))
        self.label_2.setText(_translate("Dialog", "Paid"))
        self.label_3.setText(_translate("Dialog", "Pending"))
        self.finishButton.setText(_translate("Dialog", "Finish"))
        self.pendingButton.setText(_translate("Dialog", "Pending Amount"))
        self.autofillButton.setText(_translate("Dialog", "Autofill"))
        self.label_4.setText(_translate("Dialog", "Xray"))
