# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(899, 799)
        Form.setMinimumSize(QtCore.QSize(899, 799))
        Form.setMaximumSize(QtCore.QSize(899, 799))
        Form.setStyleSheet("background: #FFFFFF")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background: url(C:/Users/Asus/Desktop/bg2.png)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_2.setFont(font)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("QFrame{\n"
"    background: url()\n"
"}\n"
"\n"
"QPushButton {\n"
"  -webkit-border-radius: 23;\n"
"  -moz-border-radius: 23;\n"
"  border-radius: 23px;\n"
"  -webkit-box-shadow: 0px 1px 7px #666666;\n"
"  -moz-box-shadow: 0px 1px 7px #666666;\n"
"  box-shadow: 0px 1px 7px #666666;\n"
"  font-size: 20px;\n"
"  padding: 10px;\n"
"  background: rgb(204,222,250,0.8);\n"
"  border: solid #1f628d 2px;\n"
"  text-decoration: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background: #3cb0fd;\n"
"  text-decoration: none;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appointments = QtWidgets.QPushButton(self.frame_2)
        self.appointments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.appointments.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.appointments.setFont(font)
        self.appointments.setObjectName("appointments")
        self.verticalLayout_2.addWidget(self.appointments)
        self.revenue = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.revenue.setFont(font)
        self.revenue.setObjectName("revenue")
        self.verticalLayout_2.addWidget(self.revenue)
        self.case_2 = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.case_2.setFont(font)
        self.case_2.setObjectName("case_2")
        self.verticalLayout_2.addWidget(self.case_2)
        self.report = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.report.setFont(font)
        self.report.setObjectName("report")
        self.verticalLayout_2.addWidget(self.report)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.appointments.setText(_translate("Form", "Appointments"))
        self.revenue.setText(_translate("Form", "Revenue"))
        self.case_2.setText(_translate("Form", "Case"))
        self.report.setText(_translate("Form", "Report"))
