# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\registerPatient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(886, 752)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(140, 310, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(140, 430, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(250, 90, 481, 22))
        self.name.setObjectName("name")
        self.phoneno = QtWidgets.QLineEdit(Dialog)
        self.phoneno.setGeometry(QtCore.QRect(250, 140, 481, 22))
        self.phoneno.setObjectName("phoneno")
        self.address = QtWidgets.QTextEdit(Dialog)
        self.address.setGeometry(QtCore.QRect(250, 190, 481, 87))
        self.address.setTabChangesFocus(True)
        self.address.setObjectName("address")
        self.history = QtWidgets.QTextEdit(Dialog)
        self.history.setGeometry(QtCore.QRect(250, 310, 481, 87))
        self.history.setTabChangesFocus(True)
        self.history.setObjectName("history")
        self.N_O = QtWidgets.QComboBox(Dialog)
        self.N_O.setGeometry(QtCore.QRect(250, 430, 73, 22))
        self.N_O.setObjectName("N_O")
        self.N_O.addItem("")
        self.N_O.addItem("")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(250, 520, 150, 28))
        self.addButton.setObjectName("addButton")
        self.backButton = QtWidgets.QPushButton(Dialog)
        self.backButton.setGeometry(QtCore.QRect(590, 520, 150, 28))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_2.setText(_translate("Dialog", "Phone No."))
        self.label_3.setText(_translate("Dialog", "Address"))
        self.label_4.setText(_translate("Dialog", "History"))
        self.label_5.setText(_translate("Dialog", "Case"))
        self.N_O.setItemText(0, _translate("Dialog", "N"))
        self.N_O.setItemText(1, _translate("Dialog", "O"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.backButton.setText(_translate("Dialog", "Back"))
