# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\xray.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(784, 610)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.path = QtWidgets.QLineEdit(Dialog)
        self.path.setGeometry(QtCore.QRect(150, 200, 400, 30))
        self.path.setObjectName("path")
        self.browseButton = QtWidgets.QPushButton(Dialog)
        self.browseButton.setGeometry(QtCore.QRect(560, 200, 93, 28))
        self.browseButton.setObjectName("browseButton")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(160, 350, 110, 30))
        self.addButton.setObjectName("addButton")
        self.nextButton = QtWidgets.QPushButton(Dialog)
        self.nextButton.setGeometry(QtCore.QRect(490, 350, 110, 28))
        self.nextButton.setObjectName("nextButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browseButton.setText(_translate("Dialog", "Browse"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.nextButton.setText(_translate("Dialog", "Next / Skip "))
